-- Foreman Turtle startup.lua v11
-- No Ctrl+T lockout. Safer state, GPS diagnostics, listening recovery.
local PROTOCOL="TurtleTeamNet"; local STATE_FILE="foreman_state.dat"; local role="foreman"; local id=os.getComputerID()
local modemSide,controllerId
local state={role=role,status="IDLE",job=nil,sector=nil,lastHeartbeat=0,networkLost=false,gpsStatus="untested",lastKnownGPS=nil,error=nil}
local function normalize() state.role=role; state.status=state.status or "IDLE"; state.networkLost=state.networkLost or false; state.gpsStatus=state.gpsStatus or "untested" end
local function save() normalize(); local f=fs.open(STATE_FILE,"w"); if f then f.write(textutils.serialize(state)); f.close() end end
local function load() if fs.exists(STATE_FILE) then local f=fs.open(STATE_FILE,"r"); local s=f.readAll(); f.close(); local t=textutils.unserialize(s); if type(t)=="table" then for k,v in pairs(t) do state[k]=v end end end; normalize() end
local function findModem() for _,side in ipairs(peripheral.getNames()) do if peripheral.getType(side)=="modem" then return side end end end
local function gpsTry(timeout) local x,y,z=gps.locate(timeout or 3); if x then state.lastKnownGPS={x=math.floor(x+0.5),y=math.floor(y+0.5),z=math.floor(z+0.5)}; state.gpsStatus="ok"; save(); return state.lastKnownGPS end state.gpsStatus="unavailable"; save(); return nil end
local function status(msg) term.clear(); term.setCursorPos(1,1); print("Foreman Turtle #"..id); print("Status: "..tostring(state.status)); print("Controller: "..tostring(controllerId)); if state.job then print("Job: "..state.job.id.." Sector: "..(state.sector and state.sector.id or "?")) end; print("GPS: "..tostring(state.gpsStatus)); if msg then print(msg) end; if state.error then print("ERROR: "..state.error) end end
local function send(msg) if controllerId then rednet.send(controllerId,msg,PROTOCOL) else rednet.broadcast(msg,PROTOCOL) end end
local function register() rednet.broadcast({type="REGISTER",role=role,id=id,status=state.status,gps=state.lastKnownGPS,gpsStatus=state.gpsStatus},PROTOCOL) end
local function heartbeat() send({type="HEARTBEAT",role=role,id=id,status=state.status,fuel=turtle.getFuelLevel(),gps=state.lastKnownGPS,gpsStatus=state.gpsStatus,jobId=state.job and state.job.id,sectorId=state.sector and state.sector.id}) end
local function safeWaitMode(reason) state.status="IDLE"; state.networkLost=true; state.error=reason; controllerId=nil; save(); status(reason or "Network lost. Standing still and listening.") end
local function assign(msg) state.job=msg.job; state.sector=msg.sector; state.status="ASSIGNED"; state.networkLost=false; state.error=nil; save(); send({type="FOREMAN_READY",jobId=state.job and state.job.id,sectorId=state.sector and state.sector.id}) end
local function foremanWork() while true do if state.job and state.sector and state.status~="ERROR" then if state.status=="ASSIGNED" then state.status="ANCHORING"; save(); send({type="FOREMAN_READY",jobId=state.job.id,sectorId=state.sector.id}) elseif state.status=="ANCHORING" then send({type="CHUNK_ANCHORED",jobId=state.job.id,sectorId=state.sector.id}); state.status="WAITING_FOR_MINER"; save() elseif state.status=="WAITING_FOR_MINER" then sleep(1) else sleep(1) end else sleep(1) end end end
local function netLoop() register(); local lastAck=os.clock(); local lastReg=os.clock(); while true do local sender,msg=rednet.receive(PROTOCOL,1); if type(msg)=="table" then if msg.type=="REGISTER_ACK" then controllerId=sender; lastAck=os.clock(); state.networkLost=false; if state.job then send({type="REQUEST_ASSIGNMENT",role=role,id=id}) end elseif msg.type=="ROLL_CALL" then rednet.send(sender,{type="ROLL_CALL_RESPONSE",role=role,id=id,status=state.status,fuel=turtle.getFuelLevel(),gps=state.lastKnownGPS,gpsStatus=state.gpsStatus},PROTOCOL) elseif msg.type=="ASSIGN_JOB" or msg.type=="RESTORE_JOB" then controllerId=sender; assign(msg) elseif msg.type=="PAUSE_JOB" then state.status="IDLE"; save() elseif msg.type=="RESUME_JOB" and state.job then state.status="ASSIGNED"; save() elseif msg.type=="CANCEL_JOB" then state={role=role,status="IDLE",networkLost=false,gpsStatus=state.gpsStatus,lastKnownGPS=state.lastKnownGPS}; save() elseif msg.type=="MINER_SAFE" then send({type="MINER_SAFE",jobId=state.job and state.job.id,sectorId=state.sector and state.sector.id}) end end; if os.clock()-lastAck>30 and controllerId then safeWaitMode("Controller heartbeat missing.") end; if os.clock()-lastReg>10 then register(); lastReg=os.clock() end end end
local function heartLoop() while true do heartbeat(); status(); sleep(5) end end
load(); modemSide=findModem(); gpsTry(5); status("Boot GPS test complete."); if not modemSide then status("ERROR: No modem. Attach wireless/ender modem and reboot."); while true do sleep(5) end end; rednet.open(modemSide); parallel.waitForAny(netLoop,heartLoop,foremanWork)
